# Generated by Django 3.2.12 on 2022-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=1500)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('topics', models.TextField()),
                ('count', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
